[package]
name = "webar-rustls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
rustls = "0.23.0"
webpki-roots = "0.26.1"
